language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t hv6kyh/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true hv6kyh/react-test-app npm run test -- --coverage

after_success:
  - docker build -t hv6kyh/docker-frontend ./frontend
  - docker build -t hv6kyh/docker-backend ./backend
  - docker build -t hv6kyh/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push hv6kyh/docker-frontend
  - docker push hv6kyh/docker-backend
  - docker push hv6kyh/docker-nginx
