on:
  push:
    branches:
      - master

name: Deploy to Amazon Beanstalk

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: docker-web-app
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker build -t hv6kyh/react-test-app -f ./frontend/Dockerfile.dev ./frontend
        
        docker run -e CI=true hv6kyh/react-test-app npm run test -- --coverage
        
        docker build -t $ECR_REGISTRY/frontend:$IMAGE_TAG ./frontend
        docker build -t $ECR_REGISTRY/backend:$IMAGE_TAG ./backend
        docker build -t $ECR_REGISTRY/nginx:$IMAGE_TAG ./nginx
        
        docker push $ECR_REGISTRY/frontend:$IMAGE_TAG
        docker push $ECR_REGISTRY/backend:$IMAGE_TAG
        docker push $ECR_REGISTRY/nginx:$IMAGE_TAG
        
        docker push $ECR_REGISTRY/frontend:$IMAGE_TAG
        docker push $ECR_REGISTRY/backend:$IMAGE_TAG
        docker push $ECR_REGISTRY/nginx:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
